name = "salon-raed"
main = ".open-next/worker.js"
account_id = "ceecf663e208c1a08fea630af5517c8f"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]



[assets]
directory = ".open-next/assets"
binding = "ASSETS"


[[hyperdrive]]
binding = "HYPERDRIVE"
id = "bf865615fe534d01b2f6745bba20cdb7"
localConnectionString = "postgresql://postgres:1UvKvAhRDeLV4e9m@db.sjqgalckdhimavjcrxck.supabase.co:6543/postgres"
